//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonteCarlo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string CallPut { get; set; }
        public string Underlying { get; set; }
        public double Tenor { get; set; }
        public Nullable<double> Rebate { get; set; }
        public Nullable<double> Barrier { get; set; }
        public double Strike { get; set; }
    }
}
